import I1 from './assets/p1.png'
import I2 from './assets/p2.png'
import I3 from './assets/p3.png'
import I4 from './assets/p4.png'
import I5 from './assets/p5.png'
import I6 from './assets/p6.png'
import I7 from './assets/p7.png'
import I8 from './assets/p8.png'
import I9 from './assets/p9.png'
import I10 from './assets/p10.png'
import I11 from './assets/p11.png'
import I12 from './assets/p12.png'


export const AllData = [
    {
        id: 1,
        img: I1,
        title: "Basic Crew Neck Tee 1",
        price: "$40,00",
        brands: "Category 1",
        color: "Yellow",
        category: "One",
    },
    {
        id: 1,
        img: I2,
        title: "Basic Crew Neck Tee 2",
        price: "$20,00",
        brands: "Category 2",
        color: "Lime",
        category: "Two",
    },
    {
        id: 1,
        img: I3,
        title: "Basic Crew Neck Tee 3",
        price: "$14,00",
        brands: "Category 3",
        color: "Blue",
        category: "Three",
    },
    {
        id: 1,
        img: I4,
        title: "Basic Crew Neck Tee 4",
        price: "$9,00",
        brands: "Category 4",
        color: "Yellow",
        category: "Four",
    },
    {
        id: 1,
        img: I5,
        title: "Basic Crew Neck Tee 5",
        price: "$30,00",
        brands: "Category 5",
        color: "Teal",
        category: "Five",
    },
    {
        id: 1,
        img: I6,
        title: "Basic Crew Neck Tee 6",
        price: "$60,00",
        brands: "Category 1",
        color: "Orange",
        category: "One",
    },
    {
        id: 1,
        img: I7,
        title: "Basic Crew Neck Tee 7",
        price: "$14,00",
        brands: "Category 2",
        color: "Blue",
        category: "Two",
    },
    {
        id: 1,
        img: I8,
        title: "Basic Crew Neck Tee 8",
        price: "$30,00",
        brands: "Category 3",
        color: "Lime",
        category: "Three",
    },
    {
        id: 1,
        img: I9,
        title: "Basic Crew Neck Tee 9",
        price: "$40,00",
        brands: "Category 4",
        color: "Lime",
        category: "Four",
    },
    {
        id: 1,
        img: I10,
        title: "Basic Crew Neck Tee 10",
        price: "$20,00",
        brands: "Category 5",
        color: "Orange",
        category: "Five",
    },
    {
        id: 1,
        img: I11,
        title: "Basic Crew Neck Tee 11",
        price: "$30,00",
        brands: "Category 4",
        color: "Blue",
        category: "One",
    },
    {
        id: 1,
        img: I12,
        title: "Basic Crew Neck Tee 12",
        price: "$14,00",
        brands: "Category 3",
        color: "Teal",
        category: "Two",
    },
   
    {
        id: 1,
        img: I7,
        title: "Basic Crew Neck Tee 7",
        price: "$60,00",
        brands: "Category 4",
        color: "Blue",
        category: "Two",
    },
    {
        id: 1,
        img: I8,
        title: "Basic Crew Neck Tee 8",
        price: "$40,00",
        brands: "Category 4",
        color: "Yellow",
        category: "Three",
    },
    {
        id: 1,
        img: I9,
        title: "Basic Crew Neck Tee 9",
        price: "$30,00",
        brands: "Category 2",
        color: "Lime",
        category: "Four",
    },
    {
        id: 1,
        img: I10,
        title: "Basic Crew Neck Tee 10",
        price: "$14,00",
        brands: "Category 5",
        color: "Orange",
        category: "Five",
    },
    {
        id: 1,
        img: I11,
        title: "Basic Crew Neck Tee 11",
        price: "$30,00",
        brands: "Category 1",
        color: "Blue",
        category: "One",
    },
    {
        id: 1,
        img: I12,
        title: "Basic Crew Neck Tee 12",
        price: "$20,00",
        brands: "Category 3",
        color: "Orange",
        category: "Two",
    },
    {
        id: 1,
        img: I1,
        title: "Basic Crew Neck Tee 1",
        price: "$50,00",
        brands: "Category 2",
        color: "Orange",
        category: "One",
    },
    {
        id: 1,
        img: I2,
        title: "Basic Crew Neck Tee 2",
        price: "$20,00",
        brands: "Category 5",
        color: "Lime",
        category: "Two",
    },
    {
        id: 1,
        img: I3,
        title: "Basic Crew Neck Tee 3",
        price: "$40,00",
        brands: "Category 4",
        color: "Blue",
        category: "Three",
    },
    {
        id: 1,
        img: I4,
        title: "Basic Crew Neck Tee 4",
        price: "$9,00",
        brands: "Category 3",
        color: "Teal",
        category: "Four",
    },
    {
        id: 1,
        img: I5,
        title: "Basic Crew Neck Tee 5",
        price: "$30,00",
        brands: "Category 2",
        color: "Yellow",
        category: "Five",
    },
    {
        id: 1,
        img: I6,
        title: "Basic Crew Neck Tee 6",
        price: "$60,00",
        brands: "Category 1",
        color: "Teal",
        category: "One",
    },
    {
        id: 1,
        img: I1,
        title: "Basic Crew Neck Tee 1",
        price: "$9,00",
        brands: "Category 2",
        color: "Orange",
        category: "One",
    },
    {
        id: 1,
        img: I2,
        title: "Basic Crew Neck Tee 2",
        price: "$20,00",
        brands: "Category 5",
        color: "Lime",
        category: "Two",
    },
    {
        id: 1,
        img: I3,
        title: "Basic Crew Neck Tee 3",
        price: "$40,00",
        brands: "Category 1",
        color: "Blue",
        category: "Three",
    },
    {
        id: 1,
        img: I4,
        title: "Basic Crew Neck Tee 4",
        price: "$60,00",
        brands: "Category 3",
        color: "Lime",
        category: "Four",
    },
    {
        id: 1,
        img: I5,
        title: "Basic Crew Neck Tee 5",
        price: "$9,00",
        brands: "Category 2",
        color: "Orange",
        category: "Five",
    },
    {
        id: 1,
        img: I6,
        title: "Basic Crew Neck Tee 6",
        price: "$30,00",
        brands: "Category 1",
        color: "Yellow",
        category: "One",
    },
    {
        id: 1,
        img: I7,
        title: "Basic Crew Neck Tee 7",
        price: "$40,00",
        brands: "Category 5",
        color: "Blue",
        category: "Two",
    },
    {
        id: 1,
        img: I8,
        title: "Basic Crew Neck Tee 8",
        price: "$20,00",
        brands: "Category 3",
        color: "Yellow",
        category: "Three",
    },
    {
        id: 1,
        img: I9,
        title: "Basic Crew Neck Tee 9",
        price: "$9,00",
        brands: "Category 2",
        color: "Lime",
        category: "Four",
    },
    {
        id: 1,
        img: I10,
        title: "Basic Crew Neck Tee 10",
        price: "$20,00",
        brands: "Category 5",
        color: "Orange",
        category: "Five",
    },
    {
        id: 1,
        img: I11,
        title: "Basic Crew Neck Tee 11",
        price: "$10,00",
        brands: "Category 1",
        color: "Blue",
        category: "One",
    },
    {
        id: 1,
        img: I12,
        title: "Basic Crew Neck Tee 12",
        price: "$14,00",
        brands: "Category 3",
        color: "Orange",
        category: "Two",
    },
    {
        id: 1,
        img: I1,
        title: "Basic Crew Neck Tee 1",
        price: "$30,00",
        brands: "Category 2",
        color: "Orange",
        category: "One",
    },
    {
        id: 1,
        img: I2,
        title: "Basic Crew Neck Tee 2",
        price: "$60,00",
        brands: "Category 5",
        color: "Lime",
        category: "Two",
    },
    {
        id: 1,
        img: I3,
        title: "Basic Crew Neck Tee 3",
        price: "$14,00",
        brands: "Category 4",
        color: "Blue",
        category: "Three",
    },
    {
        id: 1,
        img: I4,
        title: "Basic Crew Neck Tee 4",
        price: "$50,00",
        brands: "Category 3",
        color: "Yellow",
        category: "Four",
    },
    {
        id: 1,
        img: I5,
        title: "Basic Crew Neck Tee 5",
        price: "$30,00",
        brands: "Category 2",
        color: "Orange",
        category: "Five",
    },
    {
        id: 1,
        img: I6,
        title: "Basic Crew Neck Tee 6",
        price: "$9,00",
        brands: "Category 1",
        color: "Orange",
        category: "One",
    },
    {
        id: 1,
        img: I1,
        title: "Basic Crew Neck Tee 1",
        price: "$20,00",
        brands: "Category 2",
        color: "Orange",
        category: "One",
    },
    {
        id: 1,
        img: I2,
        title: "Basic Crew Neck Tee 2",
        price: "$30,00",
        brands: "Category 5",
        color: "Lime",
        category: "Two",
    },
    {
        id: 1,
        img: I3,
        title: "Basic Crew Neck Tee 3",
        price: "$14,00",
        brands: "Category 1",
        color: "Blue",
        category: "Three",
    },
    {
        id: 1,
        img: I4,
        title: "Basic Crew Neck Tee 4",
        price: "$30,00",
        brands: "Category 3",
        color: "Yellow",
        category: "Four",
    },
    {
        id: 1,
        img: I5,
        title: "Basic Crew Neck Tee 5",
        price: "$9,00",
        brands: "Category 2",
        color: "Orange",
        category: "Five",
    },
    {
        id: 1,
        img: I6,
        title: "Basic Crew Neck Tee 6",
        price: "$10,00",
        brands: "Category 1",
        color: "Orange",
        category: "One",
    },
    {
        id: 1,
        img: I7,
        title: "Basic Crew Neck Tee 7",
        price: "$40,00",
        brands: "Category 5",
        color: "Blue",
        category: "Two",
    },
    {
        id: 1,
        img: I8,
        title: "Basic Crew Neck Tee 8",
        price: "$80,00",
        brands: "Category 3",
        color: "Yellow",
        category: "Three",
    },
    {
        id: 1,
        img: I9,
        title: "Basic Crew Neck Tee 9",
        price: "$90,00",
        brands: "Category 2",
        color: "Lime",
        category: "Four",
    },
    {
        id: 1,
        img: I10,
        title: "Basic Crew Neck Tee 10",
        price: "$25,00",
        brands: "Category 5",
        color: "Lime",
        category: "Five",
    },
    {
        id: 1,
        img: I11,
        title: "Basic Crew Neck Tee 11",
        price: "$30,00",
        brands: "Category 1",
        color: "Blue",
        category: "One",
    },
    {
        id: 1,
        img: I12,
        title: "Basic Crew Neck Tee 12",
        price: "$11,00",
        brands: "Category 3",
        color: "Orange",
        category: "Two",
    },
    {
        id: 1,
        img: I1,
        title: "Basic Crew Neck Tee 1",
        price: "$40,00",
        brands: "Category 2",
        color: "Orange",
        category: "One",
    },
    {
        id: 1,
        img: I2,
        title: "Basic Crew Neck Tee 2",
        price: "$20,00",
        brands: "Category 5",
        color: "Lime",
        category: "Two",
    },
    {
        id: 1,
        img: I1,
        title: "Basic Crew Neck Tee 1",
        price: "$40,00",
        brands: "Category 2",
        color: "Orange",
        category: "One",
    },
    {
        id: 1,
        img: I2,
        title: "Basic Crew Neck Tee 2",
        price: "$20,00",
        brands: "Category 5",
        color: "Lime",
        category: "Two",
    },
    {
        id: 1,
        img: I3,
        title: "Basic Crew Neck Tee 3",
        price: "$4,00",
        brands: "Category 4",
        color: "Blue",
        category: "Three",
    },
    {
        id: 1,
        img: I4,
        title: "Basic Crew Neck Tee 4",
        price: "$9,00",
        brands: "Category 3",
        color: "Yellow",
        category: "Four",
    },
    {
        id: 1,
        img: I5,
        title: "Basic Crew Neck Tee 5",
        price: "$30,00",
        brands: "Category 2",
        color: "Orange",
        category: "Five",
    },
    {
        id: 1,
        img: I1,
        title: "Basic Crew Neck Tee 1",
        price: "$40,00",
        brands: "Category 2",
        color: "Orange",
        category: "One",
    },
    {
        id: 1,
        img: I2,
        title: "Basic Crew Neck Tee 2",
        price: "$20,00",
        brands: "Category 5",
        color: "Lime",
        category: "Two",
    },
    {
        id: 1,
        img: I3,
        title: "Basic Crew Neck Tee 3",
        price: "$4,00",
        brands: "Category 4",
        color: "Blue",
        category: "Three",
    },
    {
        id: 1,
        img: I4,
        title: "Basic Crew Neck Tee 4",
        price: "$9,00",
        brands: "Category 3",
        color: "Yellow",
        category: "Four",
    },
    {
        id: 1,
        img: I5,
        title: "Basic Crew Neck Tee 5",
        price: "$30,00",
        brands: "Category 2",
        color: "Orange",
        category: "Five",
    },
    {
        id: 1,
        img: I6,
        title: "Basic Crew Neck Tee 6",
        price: "$60,00",
        brands: "Category 1",
        color: "Orange",
        category: "One",
    },
    {
        id: 1,
        img: I6,
        title: "Basic Crew Neck Tee 2",
        price: "$60,00",
        brands: "Category 3",
        color: "Orange",
        category: "One",
    },
    {
        id: 1,
        img: I3,
        title: "Basic Crew Neck Tee 3",
        price: "$4,00",
        brands: "Category 4",
        color: "Blue",
        category: "Three",
    },
    {
        id: 1,
        img: I4,
        title: "Basic Crew Neck Tee 4",
        price: "$9,00",
        brands: "Category 3",
        color: "Yellow",
        category: "Four",
    },
    {
        id: 1,
        img: I5,
        title: "Basic Crew Neck Tee 5",
        price: "$30,00",
        brands: "Category 2",
        color: "Orange",
        category: "Five",
    },
    {
        id: 1,
        img: I6,
        title: "Basic Crew Neck Tee 6",
        price: "$60,00",
        brands: "Category 1",
        color: "Orange",
        category: "One",
    },
    
]